In [9]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

In [10]:

# Задаємо координати вершин куба
cube_vertices = np.array([
    [4, 6, 2],
    [6, 6, 2],
    [6, 8, 2],
    [4, 8, 2],
    [4, 6, 4],
    [6, 6, 4],
    [6, 8, 4],
    [4, 8, 4]])


In [11]:

cube_vertices_with_ones = np.hstack([cube_vertices, np.ones((cube_vertices.shape[0], 1))])
print(cube_vertices_with_ones[0,:-1])
print(cube_vertices_with_ones[0])


[4. 6. 2.]
[4. 6. 2. 1.]


In [12]:

scalling_matrix_1 = cube_vertices*0.5


In [13]:
point_on_line = np.array([1, 2, 3])
direction_vector = np.array([2, -1, 0])

# Generate values for the parameter t
t_values = np.linspace(-10, 10, 100)

# Calculate points on the line for each value of t
line_points = np.array([point_on_line + t * direction_vector for t in t_values])

In [16]:
point_on_line = np.array([1, 2, 3, 1])
direction_vector = np.array([2, 1, 3, 1])

matrix_move_to_center = np.array([[  1,  0,  0, -direction_vector[0]],
                            [  0,  1,  0, -direction_vector[1]],
                            [  0,  0,  1, -direction_vector[2]],
                            [  0,  0,  0, 1]])

np.dot(point_on_line, matrix_move_to_center.T)

array([-1,  1,  0,  1])

In [21]:
point_on_line = np.array([1, 2, 3])
direction_vector = np.array([2, 1, 3])
line_points = np.array([point_on_line + t * direction_vector for t in np.linspace(-8, 8, 100)])
line_points = np.hstack([line_points, np.ones((line_points.shape[0], 1))])
# Moving matrices
matrix_move_to_center = np.array([[ 1, 0, 0, -direction_vector[0]],
                            [ 0, 1, 0, -direction_vector[1]],
                            [ 0, 0, 1, -direction_vector[2]],
                            [ 0, 0, 0, 1]])


# Multiplication
line_points_to_center = np.dot(line_points, matrix_move_to_center.T)

In [24]:
line_points[0], line_points_to_center[0]

(array([-15.,  -6., -21.,   1.]), array([-17.,  -7., -24.,   1.]))

In [ ]:
direction_vector = np.array([ 2, 1, 3])